# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, verbose_name='\u4ee3\u7801')),
                ('name', models.CharField(max_length=300, verbose_name='\u540d\u79f0')),
                ('industry', models.CharField(max_length=300, verbose_name='\u6240\u5c5e\u884c\u4e1a')),
                ('area', models.CharField(max_length=300, verbose_name='\u5730\u533a')),
                ('pe', models.FloatField(verbose_name='\u5e02\u76c8\u7387')),
                ('outstanding', models.FloatField(verbose_name='\u6d41\u901a\u80a1\u672c(\u4ebf)')),
                ('totals', models.FloatField(verbose_name='\u603b\u80a1\u672c(\u4ebf)')),
                ('totalAssets', models.FloatField(verbose_name='\u6d41\u52a8\u8d44\u4ea7')),
                ('fixedAssets', models.FloatField(verbose_name='\u56fa\u5b9a\u8d44\u4ea7')),
                ('reserved', models.FloatField(verbose_name='\u516c\u79ef\u91d1')),
                ('reservedPerShare', models.FloatField(verbose_name='\u6bcf\u80a1\u516c\u79ef\u91d1')),
                ('esp', models.FloatField(verbose_name='\u6bcf\u80a1\u6536\u76ca')),
                ('bvps', models.FloatField(verbose_name='\u6bcf\u80a1\u51c0\u8d44')),
                ('pb', models.FloatField(verbose_name='\u5e02\u51c0\u7387')),
                ('timeToMarket', models.CharField(max_length=8, verbose_name='\u4e0a\u5e02\u65e5\u671f')),
                ('undp', models.FloatField(verbose_name='\u672a\u5206\u5229\u6da6')),
                ('perundp', models.FloatField(verbose_name='\u6bcf\u80a1\u672a\u5206\u914d')),
                ('rev', models.FloatField(verbose_name='\u6536\u5165\u540c\u6bd4(%)')),
                ('profit', models.FloatField(verbose_name='\u5229\u6da6\u540c\u6bd4(%)')),
                ('gpr', models.FloatField(verbose_name='\u6bdb\u5229\u7387(%)')),
                ('npr', models.FloatField(verbose_name='\u51c0\u5229\u6da6\u7387(%)')),
                ('holders', models.IntegerField(verbose_name='\u80a1\u4e1c\u4eba\u6570')),
            ],
        ),
    ]
