# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-30 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbasic',
            name='liquidAssets',
            field=models.FloatField(null=True, verbose_name='\u6d41\u52a8\u8d44\u4ea7'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='totalAssets',
            field=models.FloatField(verbose_name='\u603b\u8d44\u4ea7(\u4e07)'),
        ),
    ]
