# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-30 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0002_auto_20170930_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbasic',
            name='liquidAssets',
            field=models.FloatField(verbose_name='\u6d41\u52a8\u8d44\u4ea7'),
        ),
    ]
