# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0003_auto_20170930_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='\u5e74\u4efd')),
                ('quater', models.CharField(max_length=1, verbose_name='\u5b63\u5ea6')),
                ('code', models.CharField(max_length=7, verbose_name='\u4ee3\u7801')),
                ('name', models.CharField(max_length=300, verbose_name='\u540d\u79f0')),
                ('esp', models.FloatField(verbose_name='\u6bcf\u80a1\u6536\u76ca')),
                ('eps_yoy', models.FloatField(verbose_name='\u6bcf\u80a1\u6536\u76ca\u540c\u6bd4(%)')),
                ('bvps', models.FloatField(verbose_name='\u6bcf\u80a1\u51c0\u8d44\u4ea7')),
                ('roe', models.FloatField(verbose_name='\u51c0\u8d44\u4ea7\u6536\u76ca\u7387(%)')),
                ('epcf', models.FloatField(verbose_name='\u6bcf\u80a1\u73b0\u91d1\u6d41\u91cf(\u5143)')),
                ('net_profits', models.FloatField(verbose_name='\u51c0\u5229\u6da6(\u4e07\u5143)')),
                ('profits_yoy', models.FloatField(verbose_name='\u51c0\u5229\u6da6\u540c\u6bd4(%)')),
                ('distrib', models.FloatField(verbose_name='\u5206\u914d\u65b9\u6848')),
                ('report_date', models.CharField(max_length=8, verbose_name='\u53d1\u5e03\u65e5\u671f')),
            ],
        ),
    ]
