# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-30 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0004_reportdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportdata',
            old_name='esp',
            new_name='eps',
        ),
    ]
