# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-30 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0005_auto_20170930_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='bvps',
            field=models.FloatField(null=True, verbose_name='\u6bcf\u80a1\u51c0\u8d44\u4ea7'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='distrib',
            field=models.FloatField(null=True, verbose_name='\u5206\u914d\u65b9\u6848'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='epcf',
            field=models.FloatField(null=True, verbose_name='\u6bcf\u80a1\u73b0\u91d1\u6d41\u91cf(\u5143)'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='eps',
            field=models.FloatField(null=True, verbose_name='\u6bcf\u80a1\u6536\u76ca'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='eps_yoy',
            field=models.FloatField(null=True, verbose_name='\u6bcf\u80a1\u6536\u76ca\u540c\u6bd4(%)'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='net_profits',
            field=models.FloatField(null=True, verbose_name='\u51c0\u5229\u6da6(\u4e07\u5143)'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='profits_yoy',
            field=models.FloatField(null=True, verbose_name='\u51c0\u5229\u6da6\u540c\u6bd4(%)'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='report_date',
            field=models.CharField(max_length=8, null=True, verbose_name='\u53d1\u5e03\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='roe',
            field=models.FloatField(null=True, verbose_name='\u51c0\u8d44\u4ea7\u6536\u76ca\u7387(%)'),
        ),
    ]
