# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-01 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0006_auto_20170930_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='distrib',
            field=models.CharField(max_length=300, null=True, verbose_name='\u5206\u914d\u65b9\u6848'),
        ),
    ]
