# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-03 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0007_auto_20171001_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='\u5e74\u4efd')),
                ('quater', models.CharField(max_length=1, verbose_name='\u5b63\u5ea6')),
                ('code', models.CharField(max_length=7, verbose_name='\u4ee3\u7801')),
                ('name', models.CharField(max_length=300, verbose_name='\u540d\u79f0')),
                ('arturnover', models.FloatField(verbose_name='\u5e94\u6536\u8d26\u6b3e\u5468\u8f6c\u7387(\u6b21)')),
                ('arturndays', models.FloatField(verbose_name='\u5e94\u6536\u8d26\u6b3e\u5468\u8f6c\u5929\u6570(\u5929)')),
                ('inventory_turnover', models.FloatField(verbose_name='\u5b58\u8d27\u5468\u8f6c\u7387(\u6b21)')),
                ('inventory_days', models.FloatField(verbose_name='\u5b58\u8d27\u5468\u8f6c\u5929\u6570(\u5929)')),
                ('currentasset_turnover', models.FloatField(verbose_name='\u6d41\u52a8\u8d44\u4ea7\u5468\u8f6c\u7387(\u6b21)')),
                ('currentasset_days', models.FloatField(verbose_name='\u6d41\u52a8\u8d44\u4ea7\u5468\u8f6c\u5929\u6570(\u5929)')),
            ],
        ),
    ]
