# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0009_growthdata_profitdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profitdata',
            old_name='esp',
            new_name='eps',
        ),
    ]
