# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0010_auto_20171023_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitdata',
            name='bips',
            field=models.FloatField(null=True, verbose_name='\u6bcf\u80a1\u4e3b\u8425\u4e1a\u52a1\u6536\u5165(\u5143)'),
        ),
        migrations.AlterField(
            model_name='profitdata',
            name='business_income',
            field=models.FloatField(null=True, verbose_name='\u8425\u4e1a\u6536\u5165(\u767e\u4e07\u5143)'),
        ),
        migrations.AlterField(
            model_name='profitdata',
            name='eps',
            field=models.FloatField(null=True, verbose_name='\u6bcf\u80a1\u6536\u76ca'),
        ),
        migrations.AlterField(
            model_name='profitdata',
            name='gross_profit_rate',
            field=models.FloatField(null=True, verbose_name='\u6bdb\u5229\u7387(%)'),
        ),
        migrations.AlterField(
            model_name='profitdata',
            name='net_profit_ratio',
            field=models.FloatField(null=True, verbose_name='\u51c0\u5229\u7387(%)'),
        ),
        migrations.AlterField(
            model_name='profitdata',
            name='net_profits',
            field=models.FloatField(null=True, verbose_name='\u51c0\u5229\u6da6(\u4e07\u5143)'),
        ),
        migrations.AlterField(
            model_name='profitdata',
            name='roe',
            field=models.FloatField(null=True, verbose_name='\u51c0\u8d44\u4ea7\u6536\u76ca\u7387(%)'),
        ),
    ]
