# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-08 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0012_realtimeboxoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimeboxoffice',
            name='movie_day',
            field=models.FloatField(verbose_name='\u4e0a\u6620\u5929\u6570'),
        ),
    ]
