# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-08 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0013_auto_20171108_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimeboxoffice',
            name='time',
            field=models.CharField(max_length=20, null=True, verbose_name='\u53d1\u5e03\u65e5\u671f'),
        ),
    ]
