# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0014_auto_20171108_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBoxOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_price', models.FloatField(verbose_name='\u5e73\u5747\u7968\u4ef7')),
                ('avg_people', models.FloatField(verbose_name='\u573a\u5747\u4eba\u6b21')),
                ('box_office', models.FloatField(verbose_name='\u5355\u65e5\u7968\u623f\uff08\u4e07\uff09')),
                ('box_office_up', models.FloatField(verbose_name='\u73af\u6bd4\u53d8\u5316 \uff08%\uff09')),
                ('irank', models.IntegerField(verbose_name='\u6392\u540d')),
                ('movie_day', models.IntegerField(verbose_name='')),
                ('movie_name', models.CharField(max_length=300, verbose_name='\u5f71\u7247\u540d')),
                ('sum_box_office', models.FloatField(verbose_name='\u7d2f\u8ba1\u7968\u623f\uff08\u4e07\uff09')),
                ('wom_index', models.FloatField(verbose_name='\u53e3\u7891\u6307\u6570')),
            ],
        ),
    ]
