# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0015_dayboxoffice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayboxoffice',
            old_name='avg_people',
            new_name='avp_people',
        ),
    ]
