# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushareapi', '0016_auto_20171109_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayboxoffice',
            name='movie_day',
            field=models.IntegerField(verbose_name='\u4e0a\u6620\u5929\u6570'),
        ),
        migrations.AlterField(
            model_name='dayboxoffice',
            name='wom_index',
            field=models.CharField(max_length=10, verbose_name='\u53e3\u7891\u6307\u6570'),
        ),
    ]
